spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "4.0"


loans:
  message: "Welcome to TrelaBank prod APIs"
  contactDetails:
    name: "Example prod Contact"
    email: "example.prod.contact@gmail.com"
  onCallSupport:
    - (123) 456-7890
    - (123) 523-7890