spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName : org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  devtools:
    restart:
      enabled: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: prod

build:
  version: "2.5"

loans:
  message: "Welcome to TrelaBank loans related APIs"
  contactDetails:
    name: "Marcin Trela Developer"
    email: "marcin.trela.developer@gmailcom"
  onCallSupport:
    - (123) 456-7890
    - (123) 523-7890

server:
  port: 8090




