server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    #we change profile and get different api repsponses from config server
    active: "qa"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  config:
#    optional is given when we someteime dont need config server
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# allow all management endpoints  we want actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"




