services:


  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics","check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service


  accounts:
    image: "treladev/accounts:s6"
    container_name: accounts
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "treladev/loans:s6"
    container_name: loans
    ports:
      - "8090:8090"
    environment:
      #the spring.config.import property will be changed throgugh env variable
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "treladev/cards:s6"
    container_name: cards
    ports:
      - "9000:9000"
    environment:
      #the spring.config.import property will be changed throgugh env variable
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-configserver-config



  configserver:
    image: "treladev/configserver:s6"
    container_name: configserver
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health| grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


networks:
  trelabank:
    driver: bridge


