spring:
  application:
    name: configserver
  profiles:
    #active: native #<-- file approach
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Trela-dev/trelabank-config.git
        default-label: main
        timeout: 5
        clone-on-start: true
        force-pull: true

# file approach
#        native:
##          search-locations: "C:/Users/gaunt/Desktop/configi"
#          search-locations: "classpath:/config"


#key to encrypt
encrypt:
  key: "V-6hQYD?w0QgedUy"



server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  #prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    dev:
      trela:
        configserver: DEBUG
  #Open Telemetry
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
