server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: qa
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  devtools:
    restart:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  #Kubernetes service discovery
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  #prometheus
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true


info:
  app:
    name: cards
    description: Trela Bank Cards Application
    version: 1.0.0


logging:
  level:
    dev:
      trela:
        cards: DEBUG
  #Open Telemetry
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
