spring:
  application:
    name: gatewayserver
  config:
    #    optional is given when we someteime dont need config server
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true

          httpclient:
            connect-timeout: 1000
            response-timeout: 2s
    data:
      redis:
        connect-timeout: 2s
        host: localhost
        port: 6379
        timeout: 1s




management:
  endpoints:
    web:
      exposure:
        include: "*"
  #allow everyone to shutdown app (not recommended for production)
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: Trela Bank Gateway Server Application
    version: 1.0.


logging:
  level:
    dev:
      trela:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000